name: Tests linux

on:
  pull_request:

# Concurrency based on workflow name and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on:
      group: cupy-ci
      labels: linux-gpu

    strategy:
      matrix:
        #target: ["cuda11x-cuda-python", "cuda112", "cuda118", "cuda120", "cuda126"]
        target: ["cuda126"]
      fail-fast: false

    env:
      #CACHE_DIR: /home/runner/.cupy/kernel_cache
      CACHE_DIR: /tmp/cupy_cache
      CACHE_ARCHIVE: /tmp/${{ runner.os }}-${{ matrix.target }}-cupy-cache.tar.gz
      CACHE_KEY: ${{ runner.os }}-${{ matrix.target }}-cupy-cache  # TODO: this key might be too simple

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Check
      run: |
        echo "UBUNTU VERSION:"
        lsb_release -a
        echo "nvidia-smi:"
        nvidia-smi

    # - name: Restore Cache
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: ~/.cupy/kernel_cache
    #     key: ${{ runner.os }}-${{ matrix.target }}-cupy-cache
    #     restore-keys: |
    #       ${{ runner.os }}-cupy-cache

    - name: Setup cache
      id: gha-cupy-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.CACHE_ARCHIVE }}
        key: ${{ env.CACHE_KEY }}

    - if: ${{ steps.gha-cupy-cache.outputs.cache-hit != 'true' }}
      name: Report cache restore status
      continue-on-error: true
      run: echo "no cache found, creating a new cache..."

    - if: ${{ steps.gha-cupy-cache.outputs.cache-hit == 'true' }}
      name: Report cache restore status
      continue-on-error: true
      run: |
        echo "cache is found"
        ls -l ${{ env.CACHE_DIR }}
        ls -l ${{ env.CACHE_ARCHIVE }}

        # this is cache_get in .pfnci/linux/run.sh
        du -h "${{ env.CACHE_ARCHIVE }}" &&
          tar -x -f "${{ env.CACHE_ARCHIVE }}" -C "${{ env.CACHE_DIR }}" &&
          rm -f "${{ env.CACHE_ARCHIVE }}" || echo "WARNING: cache could not be retrieved."

        ls -l ${{ env.CACHE_DIR }}
        echo "CACHE_DIR is ${{ env.CACHE_DIR }}"
        echo "CUDA_CACHE_PATH=${{ env.CACHE_DIR }}/.nv" >> $GITHUB_ENV
        echo "CUPY_CACHE_DIR=${{ env.CACHE_DIR }}/.cupy/kernel_cache" >> $GITHUB_ENV

    - name: Update driver
      run: |
        sudo ./.pfnci/linux/update-cuda-driver.sh

    - name: build
      run: |
        ./.pfnci/linux/run.sh ${{ matrix.target }} build

    - name: test
      id: test
      run: |
        echo "CUDA_CACHE_PATH is ${CUDA_CACHE_PATH}"
        echo "CUPY_CACHE_DIR is ${CUPY_CACHE_DIR}"
        ./.pfnci/linux/run.sh ${{ matrix.target }} test
        
        # this is cache_put in .pfnci/linux/run.sh
        tar -c -f "${{ env.CACHE_ARCHIVE }}" -C "${{ env.CACHE_DIR }}" .
        du -h "${{ env.CACHE_ARCHIVE }}"
      env:
        CUPY_NVCC_GENERATE_CODE: "arch=compute_75,code=sm_75"
        GPU: 1

    # - name: Save Cache
    #   if: always()
    #   uses: actions/cache/save@v4
    #   with:
    #     path: ~/.cupy/kernel_cache
    #     key: ${{ runner.os }}-${{ matrix.target }}-cupy-cache
