name: Tests

on:
  pull_request:

# Concurrency based on workflow name and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on:
      group: cupy-ci
      labels: linux-gpu

    strategy:
      matrix:
        target: ["cuda-example", "cuda11x-cuda-python", "cuda11x-cuda-python", "cuda112", "cuda118", "cuda118.multi", "cuda120", "cuda120.multi", "cuda126", "cuda126.multi"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Check
      run: |
        echo "UBUNTU VERSION:"
        lsb_release -a
        echo "nvidia-smi:"
        nvidia-smi


    - name: Update driver
      run: |
        sudo ./.pfnci/linux/update-cuda-driver.sh

    - name: Test
      id: test
      run: |
        ./.pfnci/linux/run.sh ${{ matrix.target }} build test
