name: test

on:
  pull_request:

# Concurrency based on workflow name and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on:
      group: cupy-ci
      labels: linux-gpu

    strategy:
      matrix:
        target: ["cuda120"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Check
      run: |
        echo "UBUNTU VERSION:"
        lsb_release -a
        echo "DRIVER VERSION:"
        dpkg -l | grep cuda-drivers
        echo "nvidia-smi:"
        nvidia-smi

    - name: Test
      id: test
      run: |
        ./.pfnci/linux/run.sh ${{ matrix.target }} build test
